workerPoolSpecs:
  - machineSpec:
      machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
      imageUri: europe-west1-docker.pkg.dev/river-portfolio-484113-c9/rice-repo/rice-model:v1
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: WANDB_API_KEY
          value: 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
      command: ["uv", "run", "src/rice_cnn_classifier/train.py"]
      args: ["--epochs=10", "--batch-size=32", "--data-path=/gcs/rice_image_dataset/data/processed", "--model-dir=/gcs/rice_image_dataset/models"]
